swagger: '2.0'
info:
  title: Challenge
  description: API que fornece dados de ferramentas das tecnologias cadastradas
  version: 1.0.0
host: localhost:3000
basePath: /
tags: []
schemes:
  - http
consumes: []
produces: []
paths:
  /:
    get:
      tags: []
      description: ''
      parameters: []
      responses:
        '500':
          description: Internal Server Error
  /tools:
    get:
      tags: []
      description: ''
      parameters: []
      responses:
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      tags: []
      description: ''
      parameters: []
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /tools/{id}:
    delete:
      tags: []
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
definitions: {}
