swagger: '2.0'
info:
  title: Challenge
  description: API que fornece dados de ferramentas das tecnologias cadastradas
  version: 1.0.0
host: localhost:3000
basePath: /
tags: []
schemes:
  - http
consumes: []
produces: []
paths:
  /:
    get:
      operationId: getAllTools
      tags: []
      description: ''
      parameters: []
      responses:
        '200':
          schema:
            $ref: "#/definitions/toolsGetList200Response"
          description: OK - Successful.
        '500':
          schema:
            $ref: "#/definitions/erro500"
          description: Internal Server Error
  /tools:
    get:
      operationId: getTools
      tags: []
      description: ''
      parameters: 
        - in: query
          name: tag
          description: "Tag of the tool"
          required: true
          type: string
      responses:
        '200':
          schema:
            $ref: "#/definitions/toolsGet200Response"
          description: OK - Successful.
        '400':
          schema:
            $ref: "#/definitions/erro400"
          description: Bad Request
        '500':
          schema:
            $ref: "#/definitions/erro500"
          description: Internal Server Error
    post:
      operationId: createTools
      tags: []
      description: ''
      parameters:
        - schema:
            $ref: "#/definitions/toolsPostRequest"
          in: body
          name: Payload
          description: "Create tools"
          required: true
      responses:
        '201':
          schema:
            $ref: "#/definitions/toolsPost201Response"
          description: Created
        '400':
          schema:
            $ref: "#/definitions/erro400"
          description: Bad Request
        '500':
          schema:
            $ref: "#/definitions/erro500"
          description: Internal Server Error
  /tools/{id}:
    delete:
      operationId: removeTools
      tags: []
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '204':
          description: No Content
        '404':
          schema:
            $ref: "#/definitions/erro404"
          description: Not Found
        '500':
          schema:
            $ref: "#/definitions/erro500"
          description: Internal Server Error
definitions:
  erro404:
    type: object
    properties:
      message:
        type: string
        example: "Recurso não encontrado"
  erro400:
    type: object
    properties:
      message:
        type: string
        example: "Parametros de query não preenchidos!"
  erro500:
    type: object
    properties:
      message:
        type: string
        example: "Parametros de query não preenchidos!"
  toolsPost201Response:
    type: object
    properties:
      id:
        type: string
        example: "teste"
      title:
        type: string
        example: "teste"
      link:
        type: string
        example: "teste"
      description:
        type: string
        example: "teste"
      tags:
        type: string
        example: "teste"
  toolsGet200Response:
    type: object
    properties:
      _id:
        type: string
        example: "teste"
      title:
        type: string
        example: "teste"
      link:
        type: string
        example: "teste"
      description:
        type: string
        example: "teste"
      tags:
        type: string
        example: "teste"
  toolsGetList200Response:
    type: array
    items:
      type: object
      properties:
        _id:
          type: string
          example: "teste"
        title:
          type: string
          example: "teste"
        link:
          type: string
          example: "teste"
        description:
          type: string
          example: "teste"
        tags:
          type: string
          example: "teste"
  toolsPostRequest:
    type: object
    properties:
      title:
        type: string
        example: "teste"
      link:
        type: string
        example: "teste"
      description:
        type: string
        example: "teste"
      tags:
        type: string
        example: "teste"